### ISSUE TITLE
Statement of Work

### ISSUE THREAD

**Issue by lila-sahar** [eCapitalAdvisors/Incorta_templates#1]
**_Project Plan:_**
- [x] Create BDS templates within Incorta

**_Procurement requirements:_**
- [x] Download Anaconda
- [x] Install R studio within Anaconda
- [ ] Install Sparklyr within Anaconda (BUST)
- [x] Redownload R studio
- [x] Install Sparklyr in R Studio
